# Clones the repository which then begins with validating the assets,
# and then creates a new comment to let the contributor know if the validation has passed or failed.

name: Validate Assets

on:
  pull_request_target:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate Assets
        id: validate
        uses: repository/figura-assets-validator@v1
        with:
          path: v2
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ secrets.GH_BOT_TOKEN && 'figuramcbot' || 'github-actions[bot]' }}
          body-includes: <!-- assets-validate-result -->

      - name: Format Date
        run: |
          echo "TIME=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Create/Update Comment
        uses: peter-evans/create-or-update-comment@v3
        if: steps.validate.outputs.has_issues == 'true' || (steps.validate.outputs.has_issues == 'false' && steps.fc.outputs.comment-id != '')
        env:
          PASS_MESSAGE: |
            All issues have been resolved! 🎉
          FAIL_MESSAGE: |
            # ⚠️ Validation Failed ⚠️
            Issues were detected in your changes, please fix them before merging 🥺🙏

            ${{ steps.validate.outputs.issues_table }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.GH_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          body: |
            <!-- assets-validate-result -->
            ${{ steps.validate.outputs.has_issues == 'true' && env.FAIL_MESSAGE || env.PASS_MESSAGE }}

            Last run at `${{ env.TIME }} UTC` on commit ${{ github.sha }}

      - name: Fail Workflow
        if: steps.validate.outputs.has_issues == 'true'
        run: exit 1